services:
  postgres_db:
    image: postgres
    restart: always
    container_name: postgres_db
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

volumes:
  postgres-data:
    driver: cio
    driver_opts:
      profile: 'POSTGRESQL'
